### ISSUE TITLE
Dns setting not working for build 107 after the separation by apps

### ISSUE THREAD

**Issue by sklchan** [hklcf/Adhell3#1]
Hi,  the dns setting not working after the 107 build,  it's working during build 100.

**Comment by sklchan** [comment]
Below some of the more detail observed:
1. Dns set to the 8.8.8.8 and 8.8.4.4, enable all the apps within the list, disable and enable back the domain - the dns setting failed.
2. Dns set to the 8.8.8.8 and 8.8.4.4, disable all the apps within the list, disable and enable back the domain - some weird java error shown inside the status windows.
3. Dns set to the 8.8.8.8 and 8.8.4.4, enable only Microsoft edge app, disable and enable back the domain - no weird java error message but the dns setting still failed.

**Comment by hklcf** [comment]
Could you post a screenshot when enabling the domain? Did you see a message like "Processing DNS..."? 
When you said there is no error but dns setting failed, what does it mean? How do you test dns with microsoft edge?

**Comment by sklchan** [comment]
Hi,  i will try to post screen shot after I've upload them online. 
Yes the "Processing DNS..." message do shown inside the listing when enable the domain. 
The way i verify the dns setting working or not is try to browse to some site that confirmed block by my isp original/default dns server but allow by google dns server.

**Comment by sklchan** [comment]
https://photos.app.goo.gl/swTY7w0noxmY0anA3

**Comment by sklchan** [comment]
These are the screen shot... :)

**Comment by sklchan** [comment]
The 110 still failed to properly change the DNS for apps

**Comment by hklcf** [comment]
There is indeed a bug when dns is set but no app is selected, then there is an error message when enabling the domain rules toggle. [fixed in build 110] (https://github.com/hklcf/Adhell3/commit/e9c73fe958267f305c8d439887d3a87e1987ddeb)

**Comment by sklchan** [comment]
Yes the 110 only fixed the java error if no app been selected. But the more critical issue is the dns that been set successfully (within the adhell) is NOT working in actual situation. Is it possible to revert back to build 100 dns setting method? As it's working prior the dns setting separately by apps. I've try to recompiled the build 100 branches but it seem the compiled apk after installed crashed and failed to start.

**Comment by hklcf** [comment]
That looks fine to me. Did you clear the app cache or reboot the device?

**Comment by sklchan** [comment]
I've give up as it seem very hard to explain to you the issue.  I'll just use the vpn dns changer for now. But if you just try yourself the adhell dns change feature on those restricted site at your area then you will see what I've try to say to you.

**Comment by hklcf** [comment]
could you try opendns (208.67.222.222 and 208.67.220.220) and enable it for ms edge browser. after you reenable domain rules, check it with this site: https://welcome.opendns.com

**Comment by sklchan** [comment]
Tried still not working, below the screen shots...

https://photos.app.goo.gl/lQOtUXqBH82geW3x1

**Comment by hklcf** [comment]
Does it work with chrome or firefox or any other browser than edge ?

**Comment by sklchan** [comment]
Chrome confirmed not working as the chrome app not even showing inside the DNS setting app listing. But I will try on the firefox and feedback here later.

**Comment by sklchan** [comment]
HKLCF, it is working!!! working for Firefox, so it seem it do can set the DNS :+1: 
but FYI, it is not working for below browser:
1. Chrome - Impossible to set the DNS as the Chrome app not even been listed inside the DNS setting page, but I believe the Chrome will work if it's listed within the DNS page as during the build 100 when the DNS is a 1 setting for all apps the Chrome do follow the DNS changes, not sure about Edge though.
2. Edge - Not working as the browser somehow not follow the DNS setting.
3. Samsung Internet Browser - Not showing inside the DNS setting apps listing.
4. Samsung Internet Browser Beta - YES!! Working with DNS setting.

It seem the DNS Setting page not listing out those system apps like the build in Chrome and Samsung Internet browser.

**Comment by hklcf** [comment]
https://www.androidsage.com/2018/01/25/how-to-fix-adhell-2-not-working-chrome/

can you try this?

**Comment by sklchan** [comment]
Yes the async dns already disable but still same. Fyi I'm coming from sabs the flag been disabled since then. It is possible to let the dns setting page show out all the system apps as well within its apps listing??

https://photos.app.goo.gl/Q9R4dNoMBJ9iLeC62

**Comment by hklcf** [comment]
chrome is a system app hence don't show up.

**Comment by sklchan** [comment]
can we make it to show up system apps as well??

**Comment by hklcf** [comment]
Only user apps are supported.
