### ISSUE TITLE
 Newly installed apps not showing up inside the apps list 

### ISSUE THREAD

**Issue by sklchan** [hklcf/Adhell3#2]
Hi there,  observed the apps listing incomplete for newly installed apps from play store,  example: Network Analyser

**Comment by hklcf** [comment]
try scroll down to update the list or force close the app and restart it or restart the phone.

**Comment by sklchan** [comment]
Ok the apps show in the apps list after reboot. 
Then another question, why chrome app not listed inside the dns setting apps list? It seem lots of system apps also not inside the dns  setting apps listing.

**Comment by hklcf** [comment]
You just need to define a firewall rule "com.android.chrome|*|53", enable it with the "firewall rules" toggle and don't change anything on chrome.
