### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by david082321** [hklcf/Adhell3#4]
Can you put strings from *.java to strings.xml.
I can't make the whole language translation without change string at *.java.
and if i change *.java file, ALL language will apply it.

example:
1. 
https://github.com/hklcf/Adhell3/blob/master/app/src/main/java/com/fusionjack/adhell3/fragments/AppTabFragment.java#L26
2. 
https://github.com/hklcf/Adhell3/blob/master/app/src/main/java/com/fusionjack/adhell3/fragments/ComponentTabFragment.java#L27
3. 
https://github.com/hklcf/Adhell3/blob/master/app/src/main/java/com/fusionjack/adhell3/blocker/ContentBlocker56.java#L65
https://github.com/hklcf/Adhell3/blob/master/app/src/main/java/com/fusionjack/adhell3/blocker/ContentBlocker56.java#L72
4.
https://github.com/hklcf/Adhell3/blob/master/app/src/main/java/com/fusionjack/adhell3/fragments/SettingsFragment.java#L136
https://github.com/hklcf/Adhell3/blob/master/app/src/main/java/com/fusionjack/adhell3/fragments/SettingsFragment.java#L139
and more......

else:
https://github.com/david082321/Adhell3/commits/patch-1

**Comment by ideologysec** [comment]
File bugs upstream at fusionjack's Adhell 3 repo on GitLab; this appears to be a public fork of that.
